import type {Metadata} from "next";
import localFont from 'next/font/local';
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";

const generalSans = localFont({
    src: [
        {
            path: './assets/fonts/GeneralSans/GeneralSans-Variable.ttf',
            weight: '100 900',
            style: 'normal',
        },
        {
            path: './assets/fonts/GeneralSans/GeneralSans-VariableItalic.ttf',
            weight: '100 900',
            style: 'italic',
        },
    ],
    display: 'swap',
    variable: '--font-general-sans',
});

export const metadata: Metadata = {
    title: "HarleyStreet",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${generalSans.variable} antialiased w-full min-h-screen flex flex-col`}>
            <Header/>
            <div className="grow">
                {children}
            </div>
            <Footer/>
        </body>
        </html>
    );
}
